server:
  port: 8093
spring:
  application:
    name: power-shop-search
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.94.128:3306/power_shop?characterEncoding=UTF-8
    username: root
    password: 1111
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.94.131:8848
  elasticsearch:
    rest:
      uris:
        - http://192.168.94.135:9200
        - http://192.168.94.136:9200
#索引名称
ES_INDEX_NAME: power_shop
#类型名称
ES_TYPE_NAME: item